# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wordCloud' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wordCloud

  pod 'TwitterKit'


 

  target 'wordCloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'wordCloud-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wordCloud-tvOS

  target 'wordCloud-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
